// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA6wDgIVYX7a4JX2tK9TGemkw2Xbg_GHY',
    appId: '1:664277571655:web:bf8628066f21bba583f962',
    messagingSenderId: '664277571655',
    projectId: 'agritec-553e0',
    authDomain: 'agritec-553e0.firebaseapp.com',
    storageBucket: 'agritec-553e0.firebasestorage.app',
    measurementId: 'G-VPT6HQN3MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-wXn3L1_Xt8eeR4sMpwhhuPJWiPVtOho',
    appId: '1:664277571655:android:78aae7d1b64f7d3883f962',
    messagingSenderId: '664277571655',
    projectId: 'agritec-553e0',
    storageBucket: 'agritec-553e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwPOY89RmT0zYVGP03qvoiQCpL6n3KquQ',
    appId: '1:664277571655:ios:df63c56ac8c34b1d83f962',
    messagingSenderId: '664277571655',
    projectId: 'agritec-553e0',
    storageBucket: 'agritec-553e0.firebasestorage.app',
    iosBundleId: 'com.agritec.marketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwPOY89RmT0zYVGP03qvoiQCpL6n3KquQ',
    appId: '1:664277571655:ios:df63c56ac8c34b1d83f962',
    messagingSenderId: '664277571655',
    projectId: 'agritec-553e0',
    storageBucket: 'agritec-553e0.firebasestorage.app',
    iosBundleId: 'com.agritec.marketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA6wDgIVYX7a4JX2tK9TGemkw2Xbg_GHY',
    appId: '1:664277571655:web:44d7dac2b7b75e5983f962',
    messagingSenderId: '664277571655',
    projectId: 'agritec-553e0',
    authDomain: 'agritec-553e0.firebaseapp.com',
    storageBucket: 'agritec-553e0.firebasestorage.app',
    measurementId: 'G-1ZD7FPMK55',
  );
}
