import { AssignedDelivery, Notification, DashboardAnalytics, CoverageArea, PricingTier } from '@/lib/types';

const today = new Date();
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);
const twoDaysAgo = new Date(today);
twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);
const threeDaysAgo = new Date(today);
threeDaysAgo.setDate(threeDaysAgo.getDate() - 3);

export const mockDeliveries: AssignedDelivery[] = [
  {
    id: 'DEL001',
    parentOrderId: 'ORD001',
    sellerGroupId: 'SEL001',
    sellerId: 'SELLER001',
    sellerName: 'Fresh Farms Ltd',
    sellerPhone: '+234-80-2000-0001',
    buyerId: 'BUYER001',
    buyerDisplayName: 'Nourish Foods',
    buyerPhone: '+234-80-3000-0001',
    pickupAddress: '123 Agricultural Way, Ibadan, Oyo State',
    deliveryAddress: '456 Commerce Street, Lagos, Lagos State',
    deliveryRegion: 'Lagos',
    deliveryState: 'Lagos',
    deliveryCity: 'Lagos',
    deliveryFee: 5000,
    totalChargeableWeightKg: 50,
    currentStatus: 'delivered',
    products: [
      { id: 'P001', name: 'Tomatoes (Fresh)', quantity: 100, weight: 25 },
      { id: 'P002', name: 'Bell Peppers', quantity: 50, weight: 15 },
      { id: 'P003', name: 'Onions', quantity: 200, weight: 10 },
    ],
    assignedAt: threeDaysAgo,
    updatedAt: twoDaysAgo,
    estimatedDeliveryTime: twoDaysAgo,
    actualDeliveryTime: twoDaysAgo,
    statusHistory: [
      {
        id: 'SH001',
        deliveryId: 'DEL001',
        status: 'assigned',
        description: 'Order assigned to logistics partner',
        updatedByUserId: 'USER001',
        updatedByName: 'System',
        createdAt: threeDaysAgo,
      },
      {
        id: 'SH002',
        deliveryId: 'DEL001',
        status: 'picked_up',
        description: 'Package picked up from warehouse',
        updatedByUserId: 'DRIVER001',
        updatedByName: 'Chidinma Okafor',
        createdAt: new Date(threeDaysAgo.getTime() + 2 * 60 * 60 * 1000),
      },
      {
        id: 'SH003',
        deliveryId: 'DEL001',
        status: 'in_transit',
        description: 'Package in transit to destination',
        updatedByUserId: 'DRIVER001',
        updatedByName: 'Chidinma Okafor',
        createdAt: new Date(threeDaysAgo.getTime() + 4 * 60 * 60 * 1000),
      },
      {
        id: 'SH004',
        deliveryId: 'DEL001',
        status: 'delivered',
        description: 'Package delivered successfully',
        updatedByUserId: 'DRIVER001',
        updatedByName: 'Chidinma Okafor',
        createdAt: twoDaysAgo,
      },
    ],
  },
  {
    id: 'DEL002',
    parentOrderId: 'ORD002',
    sellerGroupId: 'SEL002',
    sellerId: 'SELLER002',
    sellerName: 'Green Valley Produce',
    sellerPhone: '+234-80-2000-0002',
    buyerId: 'BUYER002',
    buyerDisplayName: 'Premium Supermarket',
    buyerPhone: '+234-80-3000-0002',
    pickupAddress: '789 Village Road, Akure, Ondo State',
    deliveryAddress: '321 Market Lane, Ibadan, Oyo State',
    deliveryRegion: 'Ibadan',
    deliveryState: 'Oyo',
    deliveryCity: 'Ibadan',
    deliveryFee: 3500,
    totalChargeableWeightKg: 35,
    currentStatus: 'in_transit',
    products: [
      { id: 'P004', name: 'Carrots', quantity: 150, weight: 20 },
      { id: 'P005', name: 'Cabbage', quantity: 80, weight: 15 },
    ],
    assignedAt: yesterday,
    updatedAt: today,
    estimatedDeliveryTime: new Date(today.getTime() + 4 * 60 * 60 * 1000),
    statusHistory: [
      {
        id: 'SH005',
        deliveryId: 'DEL002',
        status: 'assigned',
        description: 'Order assigned to logistics partner',
        updatedByUserId: 'USER001',
        updatedByName: 'System',
        createdAt: yesterday,
      },
      {
        id: 'SH006',
        deliveryId: 'DEL002',
        status: 'picked_up',
        description: 'Package picked up from warehouse',
        updatedByUserId: 'DRIVER002',
        updatedByName: 'Adeyemi Rasheed',
        createdAt: new Date(yesterday.getTime() + 3 * 60 * 60 * 1000),
      },
      {
        id: 'SH007',
        deliveryId: 'DEL002',
        status: 'in_transit',
        description: 'Package in transit to destination',
        updatedByUserId: 'DRIVER002',
        updatedByName: 'Adeyemi Rasheed',
        createdAt: new Date(today.getTime() - 2 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: 'DEL003',
    parentOrderId: 'ORD003',
    sellerGroupId: 'SEL003',
    sellerId: 'SELLER003',
    sellerName: 'Harvest Direct',
    sellerPhone: '+234-80-2000-0003',
    buyerId: 'BUYER003',
    buyerDisplayName: 'Urban Grocers',
    buyerPhone: '+234-80-3000-0003',
    pickupAddress: '555 Farm Estate, Iwo, Osun State',
    deliveryAddress: '789 Shopping Center, Abeokuta, Ogun State',
    deliveryRegion: 'Abeokuta',
    deliveryState: 'Ogun',
    deliveryCity: 'Abeokuta',
    deliveryFee: 4200,
    totalChargeableWeightKg: 45,
    currentStatus: 'pending',
    products: [
      { id: 'P006', name: 'Yam Tubers', quantity: 50, weight: 30 },
      { id: 'P007', name: 'Sweet Potatoes', quantity: 100, weight: 15 },
    ],
    assignedAt: today,
    updatedAt: today,
    estimatedDeliveryTime: new Date(today.getTime() + 24 * 60 * 60 * 1000),
    statusHistory: [
      {
        id: 'SH008',
        deliveryId: 'DEL003',
        status: 'pending',
        description: 'Waiting for pickup',
        updatedByUserId: 'USER001',
        updatedByName: 'System',
        createdAt: today,
      },
    ],
  },
  {
    id: 'DEL004',
    parentOrderId: 'ORD004',
    sellerGroupId: 'SEL001',
    sellerId: 'SELLER001',
    sellerName: 'Fresh Farms Ltd',
    sellerPhone: '+234-80-2000-0001',
    buyerId: 'BUYER004',
    buyerDisplayName: 'Restaurant Group Inc',
    buyerPhone: '+234-80-3000-0004',
    pickupAddress: '123 Agricultural Way, Ibadan, Oyo State',
    deliveryAddress: '654 Food District, Lekki, Lagos State',
    deliveryRegion: 'Lekki',
    deliveryState: 'Lagos',
    deliveryCity: 'Lekki',
    deliveryFee: 6500,
    totalChargeableWeightKg: 60,
    currentStatus: 'failed',
    products: [
      { id: 'P008', name: 'Leafy Greens Mix', quantity: 200, weight: 25 },
      { id: 'P009', name: 'Spring Onions', quantity: 300, weight: 20 },
      { id: 'P010', name: 'Fresh Herbs', quantity: 150, weight: 15 },
    ],
    assignedAt: new Date(threeDaysAgo.getTime() - 24 * 60 * 60 * 1000),
    updatedAt: yesterday,
    estimatedDeliveryTime: yesterday,
    statusHistory: [
      {
        id: 'SH009',
        deliveryId: 'DEL004',
        status: 'assigned',
        description: 'Order assigned',
        updatedByUserId: 'USER001',
        updatedByName: 'System',
        createdAt: new Date(threeDaysAgo.getTime() - 24 * 60 * 60 * 1000),
      },
      {
        id: 'SH010',
        deliveryId: 'DEL004',
        status: 'picked_up',
        description: 'Picked up',
        updatedByUserId: 'DRIVER003',
        updatedByName: 'Oluwaseun Adeleke',
        createdAt: new Date(threeDaysAgo.getTime() - 12 * 60 * 60 * 1000),
      },
      {
        id: 'SH011',
        deliveryId: 'DEL004',
        status: 'failed',
        description: 'Delivery failed - recipient not available',
        updatedByUserId: 'DRIVER003',
        updatedByName: 'Oluwaseun Adeleke',
        createdAt: yesterday,
      },
    ],
  },
  {
    id: 'DEL005',
    parentOrderId: 'ORD005',
    sellerGroupId: 'SEL002',
    sellerId: 'SELLER002',
    sellerName: 'Green Valley Produce',
    sellerPhone: '+234-80-2000-0002',
    buyerId: 'BUYER005',
    buyerDisplayName: 'Whole Foods Market',
    buyerPhone: '+234-80-3000-0005',
    pickupAddress: '789 Village Road, Akure, Ondo State',
    deliveryAddress: '852 Commercial Avenue, Benin City, Edo State',
    deliveryRegion: 'Benin City',
    deliveryState: 'Edo',
    deliveryCity: 'Benin City',
    deliveryFee: 5800,
    totalChargeableWeightKg: 55,
    currentStatus: 'assigned',
    products: [
      { id: 'P011', name: 'Cucumber', quantity: 200, weight: 30 },
      { id: 'P012', name: 'Lettuce', quantity: 100, weight: 15 },
      { id: 'P013', name: 'Radish', quantity: 80, weight: 10 },
    ],
    assignedAt: today,
    updatedAt: today,
    estimatedDeliveryTime: new Date(today.getTime() + 36 * 60 * 60 * 1000),
    statusHistory: [
      {
        id: 'SH012',
        deliveryId: 'DEL005',
        status: 'assigned',
        description: 'Order assigned to driver',
        updatedByUserId: 'USER001',
        updatedByName: 'System',
        createdAt: today,
      },
    ],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'NOT001',
    title: 'Delivery Completed',
    message: 'Delivery DEL001 has been successfully completed',
    type: 'status_update',
    read: true,
    deliveryId: 'DEL001',
    createdAt: twoDaysAgo,
  },
  {
    id: 'NOT002',
    title: 'New Delivery Assigned',
    message: 'New delivery DEL005 has been assigned to your account',
    type: 'new_delivery',
    read: false,
    deliveryId: 'DEL005',
    createdAt: today,
  },
  {
    id: 'NOT003',
    title: 'Delivery Failed',
    message: 'Delivery DEL004 failed - recipient not available',
    type: 'failed_delivery',
    read: false,
    deliveryId: 'DEL004',
    createdAt: yesterday,
  },
  {
    id: 'NOT004',
    title: 'In Transit Update',
    message: 'Delivery DEL002 is now in transit to destination',
    type: 'status_update',
    read: true,
    deliveryId: 'DEL002',
    createdAt: new Date(today.getTime() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'NOT005',
    title: 'Admin Message',
    message: 'Please update your coverage area settings for better performance',
    type: 'admin_message',
    read: false,
    createdAt: yesterday,
  },
];

export const mockAnalytics: DashboardAnalytics = {
  totalDeliveries: 5,
  deliveredCount: 1,
  failedCount: 1,
  pendingCount: 1,
  inTransitCount: 1,
  revenue: 24500,
  statusBreakdown: {
    pending: 1,
    assigned: 1,
    picked_up: 0,
    in_transit: 1,
    delivered: 1,
    failed: 1,
    cancelled: 0,
  },
  deliveriesByDate: [
    { date: '2025-01-18', count: 1 },
    { date: '2025-01-19', count: 1 },
    { date: '2025-01-20', count: 2 },
    { date: '2025-01-21', count: 1 },
    { date: '2025-01-22', count: 0 },
    { date: '2025-01-23', count: 0 },
    { date: '2025-01-24', count: 0 },
  ],
  revenueByDate: [
    { date: '2025-01-18', revenue: 5000 },
    { date: '2025-01-19', revenue: 8500 },
    { date: '2025-01-20', revenue: 16200 },
    { date: '2025-01-21', revenue: 21400 },
    { date: '2025-01-22', revenue: 24500 },
    { date: '2025-01-23', revenue: 24500 },
    { date: '2025-01-24', revenue: 24500 },
  ],
};

export const mockPricingTiers: PricingTier[] = [
  {
    id: 'TIER1',
    name: 'Light',
    basePrice: 2000,
    pricePerKg: 50,
    minWeight: 0,
    maxWeight: 20,
  },
  {
    id: 'TIER2',
    name: 'Standard',
    basePrice: 3500,
    pricePerKg: 40,
    minWeight: 20,
    maxWeight: 50,
  },
  {
    id: 'TIER3',
    name: 'Heavy',
    basePrice: 5000,
    pricePerKg: 30,
    minWeight: 50,
    maxWeight: 100,
  },
];

export const mockCoverageAreas: CoverageArea[] = [
  { id: 'LA', state: 'Lagos', cities: ['Lagos', 'Ikeja', 'Lekki', 'Abeokuta'], covered: true },
  { id: 'OY', state: 'Oyo', cities: ['Ibadan', 'Oyo', 'Iwo'], covered: true },
  { id: 'ON', state: 'Ondo', cities: ['Akure', 'Owo', 'Ile-Ife'], covered: true },
  { id: 'OG', state: 'Ogun', cities: ['Abeokuta', 'Ijebu-Ode', 'Shagamu'], covered: true },
  { id: 'ED', state: 'Edo', cities: ['Benin City', 'Ekpoma'], covered: false },
];
